In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
class BinaryNode:
    def __init__(self, value):
        self.value = value
        self.isLeaf = None
        self.truth = None
        self.leftNode = None
        self.rightNode = None

In [106]:
class Node:
    def __init__(self, value):
        self.value = value
        self.isLeaf = None
        self.truth = None
        self.children = {}

In [5]:
# generate decision tree
# Generate data based on decision tree
# dataset 1-10 features BINARY 
    # generate 100, 1000, etc
# Compare naivebayes

In [235]:

def generateTree(limit, end_chance, node, children):
    isLeaf_flip = ((np.random.random() < end_chance) or limit == 1) and node.value != -1 #it's a head
    node.isLeaf = isLeaf_flip
    if node.isLeaf:
        node.truth = np.random.randint(children, size=1)[0]
        #print("leaf ", node.truth)
        return
    #child = np.random.randint(children, size=1)[0] + 1
    child = children
    for i in range(child):
        #print("i ", i)
        node.children[i] = Node(i)
        generateTree(limit-1, np.random.random(), node.children[i], children)
"""
children = 3
head = Node(-1)
level_limit = 10
generateTree(level_limit, 0.25, head, children)
"""

In [236]:
"""
# binary
def generateTree2(limit, end_chance, node):
    isLeaf_flip = ((np.random.random() < end_chance + np.random.random() - np.random.random()) or limit == 1) and node.value != -1 #it's a head
    node.isLeaf = isLeaf_flip
    if node.isLeaf:
        node.truth = np.random.randint(2, size=1)[0]
        print("leaf ", node.truth)
        return
    node.leftNode = Node(0)
    node.rightNode = Node(1)
    print("left")
    generateTree(limit-1, end_chance, node.leftNode)
    print("right")
    generateTree(limit-1, end_chance, node.rightNode)

head = Node(-1)
generateTree(5, 0.25, head)
"""

'\n# binary\ndef generateTree2(limit, end_chance, node):\n    isLeaf_flip = ((np.random.random() < end_chance + np.random.random() - np.random.random()) or limit == 1) and node.value != -1 #it\'s a head\n    node.isLeaf = isLeaf_flip\n    if node.isLeaf:\n        node.truth = np.random.randint(2, size=1)[0]\n        print("leaf ", node.truth)\n        return\n    node.leftNode = Node(0)\n    node.rightNode = Node(1)\n    print("left")\n    generateTree(limit-1, end_chance, node.leftNode)\n    print("right")\n    generateTree(limit-1, end_chance, node.rightNode)\n\nhead = Node(-1)\ngenerateTree(5, 0.25, head)\n'

In [274]:
"""
def generateY(x, node):
    cur = node
    for i in x:
        if cur.isLeaf:
            #print("truth")
            return cur.truth
        if i == 0:
            #print("left")
            cur = cur.leftNode
        else:
            #print("right")
            cur = cur.rightNode
"""
def generateY(x, node):
    cur = node
    for i in x:
        if cur.isLeaf:
            #print("truth")
            return cur.truth
        if i in cur.children:
            #print("left")
            cur = cur.children[i]
        else: #maybe? now -1, 0, 1
            print("no")
            return -1
            
"""
data_x = np.random.randint(children, size=(100, level_limit))
#generateY([1, 1, 1, -1], head) #-1 denotes end 
data_y = [generateY(x, head) for x in data_x]
"""

In [280]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB

In [304]:

# hyperparameters
iterations = 10
data_size = 200
# increase chidlren? 
for it in range(iterations):
    print("Iteration", it)
    children = 4
    head = Node(-1)
    level_limit = 10
    generateTree(level_limit, 0.25, head, children)

    data_x = np.random.randint(children, size=(200, level_limit))
    #generateY([1, 1, 1, -1], head) #-1 denotes end 
    data_y = [generateY(x, head) for x in data_x]
    
    k = 2
    kf = KFold(n_splits=k)
    # get the average here.
    DT_cm = []
    DT_acc = []
    
    for train_index, test_index in kf.split(data_x):
        X_train, X_test = np.take(data_x, train_index, 0), np.take(data_x, test_index, 0)
        y_train, y_test = np.take(data_y, train_index, 0), np.take(data_y, test_index, 0)
        print(np.shape(y_train))
        clf = tree.DecisionTreeClassifier()
        clf = clf.fit(X_train, y_train)
        y_pred_t = clf.predict(X_train)
        print("DT")
        print("Train acc: ", accuracy_score(y_pred_t, y_train))
        y_pred = clf.predict(X_test)
        print(confusion_matrix(y_pred, y_test))
        print("Test acc: ", accuracy_score(y_pred, y_test))
        
        print("GNB")
        gnb = GaussianNB()
        gnb.fit(X_train, y_train)
        y_pred_t = gnb.predict(X_train)
        print("Train acc: ", accuracy_score(y_pred_t, y_train))
        y_pred = gnb.predict(X_test)
        print(confusion_matrix(y_pred, y_test))
        print("Test acc: ", accuracy_score(y_pred, y_test))



Iteration 0
(100,)
DT
Train acc:  1.0
[[27  0  0  0]
 [ 0 32  1  3]
 [ 0  0 27  2]
 [ 0  2  2  4]]
Test acc:  0.9
GNB
Train acc:  0.84
[[27  0  0  0]
 [ 0 25  0  0]
 [ 0  0 27  0]
 [ 0  9  3  9]]
Test acc:  0.88
(100,)
DT
Train acc:  1.0
[[22  0  0  0]
 [ 0 29  0  0]
 [ 0  2 25  2]
 [ 2  3  2 13]]
Test acc:  0.89
GNB
Train acc:  0.88
[[22  0  0  0]
 [ 0 21  0  0]
 [ 0  0 25  0]
 [ 2 13  2 15]]
Test acc:  0.83
Iteration 1
(100,)
DT
Train acc:  1.0
[[26  4  2  0]
 [ 5 29  0  1]
 [ 2  4 11  1]
 [ 0  4  4  7]]
Test acc:  0.73
GNB
Train acc:  0.73
[[18 13  2  4]
 [14 20  5  1]
 [ 0  4  9  0]
 [ 1  4  1  4]]
Test acc:  0.51
(100,)
DT
Train acc:  1.0
[[33  5  1  0]
 [ 2 23  3  8]
 [ 1  3 15  0]
 [ 0  1  0  5]]
Test acc:  0.76
GNB
Train acc:  0.58
[[14  3  1  0]
 [18 16  4  1]
 [ 2  5 11  1]
 [ 2  8  3 11]]
Test acc:  0.52
Iteration 2
(100,)
DT
Train acc:  1.0
[[35  4  0  1]
 [ 2 27  1  0]
 [ 0  0 24  0]
 [ 1  0  0  5]]
Test acc:  0.91
GNB
Train acc:  0.72
[[29  0  0  2]
 [ 0 19  0  0]
 [ 0  6

In [276]:

"""
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix
y_pred_t = clf.predict(X_train, y_train)
y_pred = clf.predict(X_test, y_test)
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
#tree.plot_tree(clf.fit(X_train, y_train))
"""

[[8 3 2]
 [1 3 4]
 [0 1 1]]
0.5217391304347826


In [277]:
"""
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
"""

[[9 5 3]
 [0 2 2]
 [0 0 2]]
0.5652173913043478


In [ ]:
# simulate this 10 - 100 times and get accuracy 

In [ ]:
# write some tests for both generateTree and generateData functions!
# Is this too easy of a problem? 
left
leaf
right
left
leaf
right
left
leaf
right
leaf